CREATE DATABASE serverapp;

USE serverapp;

CREATE TABLE region
(
    id   INTEGER PRIMARY KEY AUTO_INCREMENT,
    name VARCHAR(255) NOT NULL UNIQUE
);

CREATE TABLE country
(
    id        INTEGER PRIMARY KEY AUTO_INCREMENT,
    region_id INTEGER      NOT NULL REFERENCES region (id) ON DELETE CASCADE,
    code      VARCHAR(2)   NOT NULL,
    name      VARCHAR(255) NOT NULL
);

DROP TABLE region;
DROP TABLE country;